
export const DEFAULT_COLOR_ENUM = {
    "Green": ["mint green", "army green", "light green", "dark green", "grean", "greem", "gteen", "green ", " green"],
    "Gold": ["rose gold", "rosegold", "rose-gold"],
    "Blue": ["sky blue", "light blue", "light bule", "light b lue", "dark blue", "navy", "navy blue", "bleu", "bule", "bluw"],
    "Brown": ["coffee", "khaki", "brown", "browm", "broun", "brawn"],
    "Red": ["watermelon red", "watermellon red", "redd", "red ", "wine", "Wine"],
    "Silver": ["sliver", "silvery", "silver,clear", "silverclear", "siver", "silvre"],
    "Gray": ["dark gray", "dark grey", "grey", "gray", "graay", "graey"],
    "Clear": ["transparent", "transparant", "transperent", "transperant", "clear", "clearr", "clera"],
    "Black": ["black", "blak", "blck", "balck"],
    "White": ["white", "whit", "wite", "whtie", "while"],
    "Yellow": ["yellow", "yello", "yelow"],
    "Orange": ["orange", "orenge", "orng"],
    "Pink": ["pink", "pinc", "peenk", "champagne", "Champagne"],
    "Purple": ["purple", "purpel", "purpple", "violet"],
    "Multicolor": ["color", "colorful", "mul", "as show", "as shown"]
};

export const DEFAULT_AI_PROMPT =
    `你是一个颜色分类专家。请将以下颜色名称映射到标准类别。\n标准类别包括: Green, Gold, Blue, Brown, Red, Silver, Gray, Clear, Black, White, Yellow, Orange, Pink, Purple, Beige, Multicolor 等。\n规则:\n- 拼写错误应映射到正确颜色 (如 "bule" -> "Blue")\n- 包含多种颜色的名称 (如 "Blue,Red") 应归类为 "Multicolor"\n- 缩写需展开 (如 "GN" -> "Green")\n- 材质/纹理描述 (如 "wood", "camouflage") 归入合理颜色或 Multicolor\n- 无法判断的归入 "Multicolor"\n请返回JSON数组，格式: [{"key":"标准类别","value":"原始颜色名称"}, ...] 只返回JSON，不要其他内容。`;

export const DEFAULT_DEDUP_FIELDS = {
    colorType: '颜色类型',
    variantGroup: 'Variant Group ID',
    amazonColor: 'Color Classification',
    sku: '',
    newColName: '去重后颜色'
};

export const DEFAULT_MAPPING = JSON.stringify({
    weight: '重量(g)',
    length: '长',
    width: '宽',
    height: '高',
    material: '面料成分',
    color: '亚马逊美国站颜色'
}, null, 2);

export const DEFAULT_CODE = [
    '// ═══════════════════════════════════════════════════════════════',
    '// 变体组生成器 · 处理函数说明书（自动列识别 + 材质提取 + 颜色标准化）',
    '// ═══════════════════════════════════════════════════════════════',
    '// ',
    '// 📥 可用参数：',
    '//    rows        - 原始数据数组',
    '//    columns     - 列映射对象（如 { weight:"重量(g)", color:"颜色" }）',
    '//    skuCol      - SKU 列名',
    '//    parentCol   - 父SKU 列名',
    '//',
    '// 📤 返回值：对象数组，每个对象代表一行。',
    '//    新增字段会被自动识别并包含在"导出生成列"中。',
    '// ═══════════════════════════════════════════════════════════════',
    'return (function(rows, columns, skuCol, parentCol) {',
    '    ',
    '    // ─────────────────── 0. 工具函数 ───────────────────',
    '    const toNum = v => isNaN(parseFloat(v)) ? NaN : parseFloat(v);',
    '    ',
    '    function extractFirstMaterial(raw) {',
    '        if (!raw || typeof raw !== "string") return "";',
    '        let trimmed = raw.trim();',
    '        if (trimmed === "") return "";',
    '        let splitBySeparators = (text) => {',
    '            let normalized = text.replace(/，/g, ",").replace(/﹢/g, "+").replace(/＆/g, "&");',
    '            let parts = normalized.split(/\\s*[,+&\\/|]\\s*|\\s+and\\s+|\\s*\\+\\s*/);',
    '            let filtered = parts.filter(p => p.trim().length > 0);',
    '            return filtered.length ? filtered : [text];',
    '        };',
    '        let segments = splitBySeparators(trimmed);',
    '        let firstSegment = segments[0] ? segments[0].trim() : trimmed;',
    '        let cleaned = firstSegment.replace(/\\d+(?:\\.\\d+)?%/g, "");',
    '        const materialWordRegex = /[A-Za-z\\u00C0-\\u024F\\u0400-\\u04FF]+(?:[\\s-][A-Za-z\\u00C0-\\u024F\\u0400-\\u04FF]+)*/;',
    '        let match = cleaned.match(materialWordRegex);',
    '        if (match && match[0]) {',
    '            cleaned = match[0].trim();',
    '        } else {',
    '            let onlyAlpha = cleaned.replace(/[^\\p{L}\\s-]/gu, "").trim();',
    '            cleaned = onlyAlpha || firstSegment.replace(/[\\d%]/g, "").replace(/[^\\w\\s\\u4e00-\\u9fa5-]/g, "").trim() || firstSegment.replace(/[^\\p{L}]/gu, "").trim() || firstSegment;',
    '        }',
    '        cleaned = cleaned.replace(/\\s+/g, " ").trim();',
    '        return cleaned || "未识别";',
    '    }',
    '    ',
    '    // ─────────── 颜色标准化 ───────────',
    '    let colorExactMap = new Map();',
    '    const colorFuzzyRules = [',
    '        { regex: /^[a-z]$/i, target: "Multicolor" },',
    '        { regex: /^multiple[a-z]*$/i, target: "Multicolor" },',
    '        { regex: /^multicolour[a-z]*$/i, target: "Multicolor" },',
    '        { regex: /^multicolor[a-z]*$/i, target: "Multicolor" },',
    '        { regex: /^mixed\\s*colou?r[a-z]*$/i, target: "Multicolor" },',
    '        { regex: /^mixedcolou?r[a-z]*$/i, target: "Multicolor" },',
    '        { regex: /^mixed\\s+colou?rs?[a-z]*$/i, target: "Multicolor" },',
    '        { regex: /^mixed[\\s\\-_]?colou?r[a-z]*$/i, target: "Multicolor" },',
    '        { regex: /^mixed\\s+colors?[a-z]*$/i, target: "Multicolor" }',
    '    ];',
    '    try {',
    '        const colorEnumConfig = JSON.parse(localStorage.getItem("color_enum_config_fusion") || "{}");',
    '        for (const [category, aliases] of Object.entries(colorEnumConfig)) {',
    '            if (Array.isArray(aliases)) {',
    '                aliases.forEach(alias => {',
    '                    const key = String(alias).trim().toLowerCase();',
    '                    if (key) colorExactMap.set(key, category);',
    '                });',
    '            }',
    '        }',
    '    } catch(e) { /* 颜色配置读取失败，使用空映射 */ }',
    '    ',
    '    function normalizeColor(raw) {',
    '        if (!raw || typeof raw !== "string") return "";',
    '        const trimmed = raw.trim();',
    '        if (trimmed === "") return "";',
    '        const norm = trimmed.toLowerCase();',
    '        const mapped = colorExactMap.get(norm);',
    '        if (mapped) return mapped;',
    '        for (const rule of colorFuzzyRules) {',
    '            if (rule.regex.test(norm)) return rule.target;',
    '        }',
    '        return trimmed;',
    '    }',
    '    // ─────────── 颜色标准化结束 ───────────',
    '    ',
    '    // ─────────────────── 1. 常量定义 ───────────────────',
    '    const GRAM_TO_LB = 0.00220462;',
    '    const CM_TO_INCH = 0.393701;',
    '    ',
    '    // ─────────────────── 2. 数据分组 ───────────────────',
    '    const parentMap = new Map();',
    '    const groupInfo = new Map();',
    '    const tempRows = [];',
    '    ',
    '    for (let i = 0; i < rows.length; i++) {',
    '        const r = rows[i];',
    '        const sku = String(r[skuCol] || "").trim();',
    '        const parent = String(r[parentCol] || "").trim();',
    '        ',
    '        let groupId = parent ? (parentMap.has(parent) ? parentMap.get(parent) : sku) : sku;',
    '        if (parent && !parentMap.has(parent)) parentMap.set(parent, groupId);',
    '        ',
    '        const weightVal = r[columns.weight] !== undefined ? r[columns.weight] : "";',
    '        const net = toNum(weightVal) ? (toNum(weightVal) * GRAM_TO_LB).toFixed(2) : "";',
    '        const lengthVal = r[columns.length] !== undefined ? r[columns.length] : "";',
    '        const l = toNum(lengthVal) ? (toNum(lengthVal) * CM_TO_INCH).toFixed(2) : "";',
    '        const widthVal = r[columns.width] !== undefined ? r[columns.width] : "";',
    '        const w = toNum(widthVal) ? (toNum(widthVal) * CM_TO_INCH).toFixed(2) : "";',
    '        const heightVal = r[columns.height] !== undefined ? r[columns.height] : "";',
    '        const h = toNum(heightVal) ? (toNum(heightVal) * CM_TO_INCH).toFixed(2) : "";',
    '        ',
    '        let materialClass = "";',
    '        if (columns.material) {',
    '            const materialRaw = String(r[columns.material] || "").trim();',
    '            materialClass = materialRaw ? extractFirstMaterial(materialRaw) : "";',
    '        }',
    '        ',
    '        let colorClass = "";',
    '        if (columns.color) {',
    '            const colorRaw = String(r[columns.color] || "").trim();',
    '            colorClass = colorRaw ? normalizeColor(colorRaw) : "";',
    '        }',
    '        ',
    '        tempRows.push({',
    '            ...r,',
    '            _groupId: groupId,',
    '            _net: net,',
    '            _l: l,',
    '            _w: w,',
    '            _h: h,',
    '            _materialClass: materialClass,',
    '            _colorClass: colorClass',
    '        });',
    '        ',
    '        if (!groupInfo.has(groupId)) groupInfo.set(groupId, { indices: [] });',
    '        groupInfo.get(groupId).indices.push(i);',
    '    }',
    '    ',
    '    // ─────────────────── 3. 确定主变体 ───────────────────',
    '    for (let [gid, info] of groupInfo) {',
    '        const idxs = info.indices;',
    '        if (idxs.length === 1) {',
    '            info.primaryIdx = 0;',
    '        } else {',
    '            info.primaryIdx = 1 + Math.floor(Math.random() * (idxs.length - 1));',
    '        }',
    '    }',
    '    ',
    '    // ─────────────────── 4. 构建最终结果（包含所有生成列）───────────────────',
    '    return tempRows.map((t, i) => {',
    '        const info = groupInfo.get(t._groupId);',
    '        const pos = info.indices.indexOf(i);',
    '        return {',
    '            ...t,',
    '            "Variant Group ID": t._groupId,',
    '            "Is Primary Variant": (pos === info.primaryIdx) ? "Yes" : "No",',
    '            netContentStatement: t._net,',
    '            assembledProductLength: t._l,',
    '            assembledProductWidth: t._w,',
    '            assembledProductHeight: t._h,',
    '            "Material Classification": t._materialClass,',
    '            "Color Classification": t._colorClass',
    '        };',
    '    });',
    '})(rows, columns, skuCol, parentCol);',
    '// ═══════════════════════════════════════════════════════════════'
].join('\n');
