


(function(global) {
    'use strict';

    // 1. 全局唯一定义的数据仓库命名空间
    const ROOT_NS = '__DICTS__'; 
    global[ROOT_NS] = global[ROOT_NS] || {};

    // 2. 当前字典名称与数据
    const DICT_KEY = 'color';
    const DICT_DATA = {
  "Green": [
    "mint green",
    "army green",
    "light green",
    "dark green",
    "grean",
    "greem",
    "gteen",
    "green ",
    " green",
    "GreenWhite",
    "GreenBlue",
    "GreenGold",
    "GreenPink",
    "Green A",
    "Green B",
    "Green C",
    "Green D",
    "Green E",
    "Green F",
    "黑绿色",
    "Army-Green",
    "Emerald green",
    "Green stripes",
    "Sage green boho",
    "green-peach",
    "Green and Golden",
    "Green, Silver",
    "Green, Red, White",
    "Green,White",
    "Green, Red, Led Light Color",
    "Green + Orange",
    "Green Patina+wood Color",
    "Green - Blue - Pink - Yellow",
    "Green/Pink/White",
    "Green and Blue",
    "Green, Blue, Pink, Orange",
    "Green, White, Pink, Brown",
    "Green/White",
    "Green and White",
    "Green, Red",
    "Gold, Green",
    "Green, White",
    "green, blue",
    "Green White Red",
    "Green, Brown, Creamy White",
    "silver and green",
    "Green and Gold",
    "Green/Gold",
    "Green & Brown",
    "Grenn and Brown",
    "brown, green, champagne, white",
    "Color: Green",
    "Black, Green, Brown, White, Orange",
    "Green and Gold",
    "Sage Green and Gold",
    "Dark Moss Green",
    "Sage Green Brown Nude Cream Neutral",
    "Red, Green and White",
    "Red, Green, Blue, Orange, White",
    "Red, Green, Gold",
    "Red, green, yellow, blue",
    "Red, Green, White, Gold",
    "Orange, Green, Blue, Pink, Purple",
    "Green, Red",
    "Olive Green",
    "12 Pack Artificial Ivy Vine",
    "Boxwood Fern",
    "Herbs",
    "Olive",
    "Lime Green",
    "Christmas Green"
  ],
  "Gold": [
    "rose gold",
    "rosegold",
    "rose-gold",
    "Gold",
    "Golden",
    "Champagne Gold",
    "Brass",
    "Golden Base",
    "Goldistock",
    "Gold and Silver",
    "Copper Gold",
    "Gold, Silver, Red, Green",
    "Gold, Silver, Bronze",
    "Gold, Silver, and other vibrant hues",
    "Gold, Silver",
    "Golden,white",
    "Blue Gold",
    "Black and Gold",
    "Pink and Gold",
    "Brushed Brass",
    "bronze-colored",
    "Gold, Silver, bronze-coloured",
    "Red and Gold",
    "Antique Gold",
    "Gold and Pink Gold",
    "golden unicorn",
    "Rose Gold - Mandala",
    "Pink rose gold",
    "Rose Gold,Silver",
    "Black Gold",
    "Black Rose Gold",
    "Pink Rose Gold",
    "Green and Gold",
    "Sage Green and Gold",
    "Gold, Black",
    "Black Gold silver",
    "Yellow Brass",
    "Gold White",
    "Gold, Silver, Black",
    "Purple, Green and Gold",
    "Gold, Silver, Black",
    "Golden, Green, Red",
    "Gold White",
    "Orange, Gold, White",
    "Shiny Gold",
    "Gold and Black",
    "Black/Gold",
    "Green/Gold",
    "Red, Gold, Silver",
    "Red, Green, Gold",
    "Glitter Gold",
    "brass color"
  ],
  "Blue": [
    "sky blue",
    "light blue",
    "light bule",
    "light b lue",
    "dark blue",
    "navy",
    "navy blue",
    "bleu",
    "bule",
    "bluw",
    "Blue",
    "Blue A",
    "Blue B",
    "Blue C",
    "Blue D",
    "Blue E",
    "Blue F",
    "BlueONE",
    "BlueTWO",
    "Blueone",
    "Bluetwo",
    "Bluethree",
    "Bluefour",
    "Ligt Blue",
    "Lit Blue",
    "Light lue",
    "Light ue",
    "Light Teal",
    "Light Sky Blue",
    "Blue, Orange",
    "Blue,White",
    "blue and white",
    "Blue,white",
    "blue, silver",
    "Blue and Black",
    "Blue and White",
    "Blue Gold",
    "Green and Blue",
    "Blue, Green, Pink, Yellow",
    "Blue, Green, Multicolor, Pink, Red, Yellow",
    "Blue/Green",
    "Blue-stars",
    "Blue, White, Black, Red",
    "Blue Orange Red",
    "Antique blue and copper",
    "Blue-Green",
    "blue and gold",
    "Blue, Pink, White, Green, Navy Blue, Black",
    "Peacock Blue",
    "Provincial Blue",
    "Blue/Black",
    "Blue, brown, clear",
    "Royal Blue",
    "Navy Blue, Green",
    "Blue-Purple",
    "Porcelain Blue",
    "Blue, Black",
    "Blue Snowflakes",
    "blue, white, gold",
    "blue, pink, white, green",
    "Blue Red White",
    "Blue, Red, Yellow, Green",
    "Blue/Pink/Green",
    "White+blue",
    "Blue&khaki",
    "blue & pink",
    "Blue/Beige",
    "blue, black, gray, sky blue",
    "White and Blue",
    "Blue, Black",
    "Blue, Pink, Green, Beige",
    "Black,White,Blue,Pink",
    "White, Blue, Green",
    "Black / Blue / Green / Red",
    "Red, Blue, Orange, Pink",
    "Red, White, Blue",
    "Babyblue",
    "blue wave cutting board",
    "Blue hiking water bottle",
    "Teal Blue",
    "Blue Grey",
    "Sea Blue"
  ],
  "Brown": [
    "coffee",
    "khaki",
    "brown",
    "browm",
    "broun",
    "brawn",
    "Brown A",
    "Brown B",
    "Dark Brown",
    "Wood",
    "Seasons",
    "Kraft Brown",
    "Natural Wood",
    "Natural wood",
    "Rustic Kraft",
    "deep brown",
    "Brown New",
    "Pine Wood",
    "Wood color",
    "natural wood",
    "Brown Wood",
    "Light Wood",
    "Log Color",
    "Kraft",
    "Gradient Dark Brown",
    "Kraft paper",
    "Tan/Brown",
    "Brown/Red",
    "Black, Brown",
    "Brown and White",
    "Cognac",
    "Light Brown",
    "Dried Gourd, Wood",
    "Brown Eucalyptus Flower",
    "Natural Olive Wood",
    "Brown Wood Grain",
    "Chestnut Brown",
    "Walnut",
    "Carbonized Bamboo",
    "Natural Acacia Wood",
    "Brown Oak",
    "Natural Bamboo",
    "Natural Rattan",
    "Brown Rust Red Vintage Floral",
    "Clay Brown",
    "Sage Green Brown Nude Cream Neutral",
    "brown, green, champagne, white",
    "mainly brown",
    "Orange, Brown",
    "Orange, Red, Brown",
    "Tan",
    "TAN",
    "Light Tan",
    "antiqued bronze + natural wood",
    "Rustic Metal",
    "Oil Rubbed Bronze",
    "Original Smoked",
    "Rustic Brown",
    "Kraft Style",
    "kraft paper color",
    "Wood (Natural)",
    "Antique Copper",
    "Rusty",
    "Original wood color",
    "wooden color",
    "Acacia"
  ],
  "Red": [
    "watermelon red",
    "watermellon red",
    "redd",
    "red ",
    "wine",
    "Wine",
    "Red A",
    "Red B",
    "Red C",
    "Rose Red",
    "暗红色",
    "Burgundy",
    "Red Mainly",
    "01 Red",
    "Red, Burgundy, Beige",
    "Red, Brown, Black",
    "Red, Black",
    "Red, green, white",
    "Red,Yellow",
    "Red & Blue",
    "Red, Green, White",
    "Red, Black, Blue, Green, Yellow",
    "Red and Yellow",
    "Red&Black",
    "Red, Green, Blue, Yellow, Orange, Purple",
    "Red and Black",
    "Red Green White Blue",
    "Red, Green, Cream, Brown",
    "Red/Green/White",
    "Red-silver",
    "Red, Green, Silver",
    "Red, Yellow, Blue",
    "Red, Green",
    "Red and Gold",
    "Solid Red",
    "Silver, Red, Black",
    "Pink & Red with Green Accents",
    "Green, Red",
    "Red, White",
    "Red, Green, Blue, Orange, White",
    "red, green, yellow, blue",
    "Red, Green, Blue, Orange",
    "Brown + Red",
    "Black, Gold, Red, Silver",
    "Red Foil",
    "Red White Blue",
    "Blue Red White",
    "Green White Red",
    "Orange, Red, Yellow, Brown, Black, White, Green",
    "Red, White, Blue",
    "Red, Pink, Light Pink",
    "Red, Green, Yellow",
    "Red + Black",
    "Red, Green and White",
    "Red, Green, Gold",
    "Red, Blue, Orange, Pink",
    "Red, Yellow and Black",
    "White, Red, Green",
    "Red Black Santa Christmas Table Runner",
    "Rose Red & White",
    "Red, White, Green",
    "Red, Black, Blue",
    "Red & Green",
    "Red Laser",
    "Red Light Long GunLight",
    "Red2",
    "Bright Red",
    "Red 3 PCS",
    "mainly red",
    "brick-red"
  ],
  "Silver": [
    "sliver",
    "silvery",
    "silver,clear",
    "silverclear",
    "siver",
    "silvre",
    "Silver",
    "Silver A",
    "Silver B",
    "Silver C",
    "Silver finish",
    "Silver B 50pcs",
    "Chrome",
    "Holographic Silver",
    "Chromium Plated",
    "silver tone",
    "Metallic Silver",
    "Silver-120pcs",
    "Pearl Nickel",
    "Nickel",
    "Silver colored",
    "Brushed Aluminum",
    "Nickel plated",
    "Silver,Red",
    "Tan, Silver",
    "Silver(new)",
    "Slive",
    "Silver, Black, White, Red, Pink, Orange, Yellow, Green, Sky Blue, Light Purple",
    "Antique Silver",
    "Silver, Red, Black",
    "Silver Angel Wings and Red Ribbons",
    "Purple, Silver",
    "Black and Silver",
    "Rose Gold,Silver",
    "Silver Grey",
    "Black Gold silver",
    "Silver-gray",
    "Silver/Black",
    "Brushed Nickel",
    "Silver-black",
    "Bright Stainless Steel",
    "Silver Diamond",
    "Silver and wood-colored",
    "Glitter Silver",
    "Glitter",
    "Stainless steel silver",
    "Silver - 2 Pcs",
    "12 Inch Steel Pan",
    "Stainless Steel/Wood Handle",
    "brushed silver"
  ],
  "Gray": [
    "dark gray",
    "dark grey",
    "grey",
    "gray",
    "graay",
    "graey",
    "Gray",
    "Pewter",
    "Charcoal",
    "Smoke Gray",
    "Light Grey",
    "Graphite",
    "gray, white",
    "gray, black, white",
    "Black/Gray/Light Gray",
    "gray on black",
    "Gray, Black",
    "Dark grey and Marble",
    "Gray & White",
    "Silver Grey",
    "anthracite gray",
    "Gray And Wood",
    "Gray, Black",
    "Black,Gray,White",
    "grey(YN372)",
    "blue, black, gray, sky blue",
    "Charcoal, Graphite",
    "Titanium Grey",
    "Silver Gray"
  ],
  "Clear": [
    "transparent",
    "transparant",
    "transperent",
    "transperant",
    "clear",
    "clearr",
    "clera",
    "Clear D",
    "Clear C",
    "Clear B",
    "Clear A",
    "Diamond",
    "Clear / Transparent",
    "Crystal Clear",
    "Translucent",
    "Transluent",
    "Frosted Clear",
    "colourless",
    "Clear and Black",
    "Clear, Silver",
    "Clear, White",
    "White, Clear",
    "Milky white translucent",
    "clear glass",
    "Clear white",
    "Colorless",
    "Color: Clear",
    "Color: transparent",
    "Transparent Black",
    "Transparent White",
    "Clear - Black Print",
    "Clear with Multicolor inside",
    "White clear",
    "Clear, Pink, Green, Blue",
    "Clear, Glass",
    "Clear, Distressed Rust Color",
    "burlywood transparent",
    "Clear, White",
    "Clear, Warm White",
    "Frosted",
    "Clear,Transparent",
    "tansparent",
    "transparent color",
    "Clear Grid",
    "Unflavored",
    "Transparent with Yellow Markings",
    "Crystal Ice",
    "Clear/Transparent"
  ],
  "Black": [
    "black",
    "blak",
    "blck",
    "balck",
    "Black A",
    "Black B",
    "Black C",
    "Black D",
    "Matte Black",
    "Rustic Black",
    "Black-1 pack",
    "Black-44",
    "Graphite",
    "Black 2 people",
    "Blcak",
    "Black (Silver Trim)",
    "Black ,2pcs",
    "Dark Black",
    "Black Oxide",
    "02-black",
    "black body",
    "Black 40KG-1",
    "Porous Black",
    "Black-01",
    "matte-black",
    "US Navy black",
    "carbon leather black",
    "Black, Silver",
    "Black, Orange",
    "Black, Red",
    "Black and Gold",
    "Black, Beige, Light Brown, Dark Brown",
    "Black, Gold",
    "Black White",
    "Black&Red",
    "Black & Red",
    "Black, White",
    "Black&White",
    "Black and Red",
    "Black, Brown",
    "Black With Red Stitching",
    "Black And Yellow",
    "Black Red Western",
    "gray on black",
    "Silver, Red, Black",
    "Black, Silver, Yellow",
    "Black, Light Green, Orange, Red, Purple, Royal Blue, Dark Green",
    "Black and Silver",
    "Black Rose Gold",
    "Black Gold",
    "Gray, Black",
    "Black, Gold, Red, Silver",
    "Black Spray",
    "Pink&Black",
    "Black/Gray/White",
    "Transparent Black",
    "black gold",
    "Black - We Hooked The Best Papa",
    "Black,Orange,Purple",
    "Black Red",
    "Black, Green, Brown, White, Orange",
    "Silver/Black",
    "Black & Beige",
    "Black Gold silver",
    "Black / Blue / Green / Red",
    "Black/Gold",
    "Black,yellow",
    "Red, Black, Blue",
    "Orange, Black, White, Green",
    "black, purple, white, orange",
    "Black, Green, Brown, White, Orange",
    "Clear - Black Print",
    "blue, black, gray, sky blue",
    "Black Color",
    "1hl-ykk-lbr2-black-1ml",
    "160L, Black",
    "Matt Black",
    "Square Black 4 Player",
    "Black-2 pcs",
    "Metal black",
    "Mainly Black",
    "black or gray",
    "Black-32QT",
    "Black-110V Plug",
    "Black-1Pack",
    "Black Coated Finish"
  ],
  "White": [
    "white",
    "whit",
    "wite",
    "whtie",
    "while",
    "White A",
    "White B",
    "White C",
    "White D",
    "White E",
    "White F",
    "White G",
    "White H",
    "Whiteone",
    "Whitetwo",
    "Whitethree",
    "Whitefour",
    "Whitefive",
    "Whitesix",
    "White.",
    "E26 Warm White",
    "Warm White",
    "Pure White",
    "Matte White",
    "cold white",
    "White, Yellow",
    "White, Brown With Mixed Pattern 1",
    "White and Red",
    "White, Pink",
    "White/black",
    "White, Navy Blue",
    "White Pink Rose",
    "White, Clear",
    "Morden Milky White",
    "Daylight White",
    "Clear white",
    "White, Black, Gold",
    "Green and White",
    "White Marble",
    "White with multicolored designs",
    "Creamy White",
    "White and Yellow",
    "White clear",
    "White clear",
    "Green White Red",
    "White Pumpkin",
    "White, brown",
    "Off-white",
    "White-4 Pcs",
    "Pink, White, Silver",
    "White, Red, Green",
    "Whitewashed Beige",
    "Transparent White",
    "White and Blue",
    "White Ceramic Cake Stand",
    "Pink-white",
    "Off White orange Patterns",
    "Color: White",
    "Gold White",
    "Cream",
    "White, Red",
    "White, Blue, Green",
    "distressed white",
    "Red, White, Green",
    "White Color",
    "pearly",
    "Cool White",
    "1pc white Miniatures Paint rack",
    "White cat",
    "love white elephant",
    "Cream white",
    "White S"
  ],
  "Yellow": [
    "yellow",
    "yello",
    "yelow",
    "Yellow A",
    "Yellow B",
    "Yellow C",
    "Sunny Yellow",
    "Shiny Yellow",
    "Yellow, Black",
    "Yellow, Red, Green",
    "Yellow, Black, Orange",
    "Yellow, Green, Blue, Pink, Orange, Red",
    "Yellow + Black",
    "Yellow-Thank Cards 25 Sets",
    "light yellow",
    "Black, Silver, Yellow",
    "Orange and Yellow",
    "Lemon Yellow",
    "Yellow Brass",
    "White and Yellow",
    "Yellow Gingerbread Man",
    "Yellow,red",
    "yellow and white",
    "Black,yellow",
    "Light Yellow",
    "Red, Yellow and Black",
    "Red, Yellow, Dark Blue, Sky Blue, Dark Green, Light Green, Black, Gold",
    "31\" Yellow Bird of Paradise",
    "yellow low",
    "yellow(QY109)",
    "Yellow with Reflective and Glossy Coatings",
    "Main Yellow",
    "Salted Yellow"
  ],
  "Orange": [
    "orange",
    "orenge",
    "orng",
    "Orange A",
    "Orange B",
    "Orange C",
    "Orange color",
    "OrangeA",
    "OrangeB",
    "OrangeC",
    "Pumpkin 3",
    "Orange and Black",
    "Orange 2 Person Tent 2024",
    "Orange, Green, Blue, Pink, Purple",
    "Orange, Red, Yellow, Brown, Black, White, Green",
    "Orange, Buffalo Plaid",
    "Orange and Yellow",
    "Orange, Brown",
    "Orange,brom",
    "Orange, Burgundy, Gold, Cream, Yellow",
    "Black,Orange,Purple",
    "Orange, Black, White, Green",
    "Orange, Gold, White",
    "Pink, Orange, Black",
    "Off White orange Patterns",
    "Red, Blue, Orange, Pink",
    "Burnt Orange 1stem-28pcs",
    "Fall Pumpkin"
  ],
  "Pink": [
    "pink",
    "pinc",
    "peenk",
    "champagne",
    "Champagne",
    "Hot Pink",
    "Pink A",
    "Pink B",
    "dual Pink",
    "pin",
    "Light pink",
    "Pink Sakura",
    "Rose",
    "1.5inch Pink",
    "Flamingo",
    "Dusty Pink",
    "Pink, Cyan, Yellow, Orange, Green, Purple",
    "Pink, Blue, Purple",
    "Pink and Gold",
    "Pink and Green",
    "Pink, Blue",
    "Pink & Red with Green Accents",
    "Gold and Pink Gold",
    "Pink rose gold",
    "Rose Gold - Mandala",
    "Pink Blue Ombre",
    "Pink & Green",
    "Pink Rose Gold",
    "Pink Bachelorette Straw",
    "Red, Pink, Light Pink",
    "Rose Gold, Pink, Gold",
    "Diamond Pink",
    "Pink, White, Silver",
    "Pink/Blue/Green",
    "Pink Rose",
    "Pink and Rose",
    "Pink, white",
    "Pink Blue and Green",
    "Pink-white",
    "Color: Pink",
    "Color: pastel color, pink and green",
    "Blue, Pink, White, Green, Navy Blue, Black",
    "Black,White,Blue,Pink",
    "Clear, Pink, Green, Blue",
    "pink and purple",
    "pink and white",
    "Pink, Green, Purple, Blue, White, Orange, Beige, Salmon Pink",
    "Gradient Pink",
    "Boho Pink",
    "pastel pink"
  ],
  "Purple": [
    "purple",
    "purpel",
    "purpple",
    "violet",
    "PurplePink",
    "PurpleWhite",
    "紫色",
    "rose Purple",
    "lavender",
    "Best Seller: Purple",
    "Purple, Red",
    "Purple, Rose, Blue, Green, Yellow",
    "purple, black, orange",
    "purple, brown, black",
    "purple, pink, blue, green, yellow, etc.",
    "purple, multicolor",
    "Purple, Silver",
    "Purple, Orange, Black, Green",
    "Purple & Blue",
    "Purple pink blue",
    "Blue-Purple",
    "purple, yellow, orange, blue, green, pink",
    "black, purple, white, orange",
    "Black,Orange,Purple",
    "Purple, Green and Gold",
    "Pink, Green, Purple, Blue, White, Orange, Beige, Salmon Pink",
    "Light Purple 2pcs"
  ],
  "Multicolor": [],
  "Bronze": [
    "Bronze",
    "Antique Bronze",
    "bronze-colored"
  ],
  "Beige": [
    "Beige",
    "Beige A",
    "Pinkish Beige",
    "ivory",
    "Natural",
    "natural",
    "Beige, Pink, Gray",
    "Beige Chicken",
    "Blue, Pink, Green, Beige",
    "Whitewashed Beige",
    "Natural/Cream & Black Pattern",
    "clear and beige",
    "Biege",
    "Natural Colour",
    "Manila",
    "Beige (2 Pack)",
    "natural color",
    "flaxen"
  ]
};

    // 3. 注册到命名空间，并设为只读冻结（防止被意外篡改）
    global[ROOT_NS][DICT_KEY] = Object.freeze(DICT_DATA);

})(typeof window !== 'undefined' ? window : globalThis);